id: P004320
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG6158
  title: ཉེས་ཁྲིམས་ལ་འཇུག་པའི་སྒོ།
  author: ''
  volumes:
    9fcb7a74ff1d49679c42fa483d47b721:
      image_group_id: I1KG8409
      title: ''
      volume_number: 1
      total_pages: 158
      base_file: v001.txt
