id: I1DD40883
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T07:22:18+00:00'
last_modified: '2022-06-07T21:58:01.612816+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6158
  title: ཉེས་ཁྲིམས་ལ་འཇུག་པའི་སྒོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    091D:
      image_group_id: I1KG8409
      title: ''
      total_pages: 158
      order: 1
      base_file: 091D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
